config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'money_pots#index'

  resources :money_pots do
    resources :transactions
  end

end

app/models/money_pot.rb
class MoneyPot < ActiveRecord::Base
  has_many :transactions, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :transactions
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :money_pot
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :money_pots, dependent: :destroy
  has_many :transactions, through: :money_pots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/money_pots_controller.rb
class MoneyPotsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @money_pots = MoneyPot.where(isActive: true).order("created_at ASC")
  end

  def new
    @money_pot = MoneyPot.new
  end

  def create
    @money_pot = MoneyPot.new(money_pot_params)

    if @money_pot.save
      redirect_to @money_pot
    else
      flash.now[:error] = "Could not save money pot"
      render action: "new"
    end
  end

  def show
    @money_pot = get_current_money_pot
    @transaction = Transaction.new
    @transactions = @money_pot.transactions.order("created_at DESC")
    @transactions_value = @transactions.sum(:value)
  end

  def edit
    @money_pot = get_current_money_pot
  end

  def update
    money_pot = get_current_money_pot
    money_pot.update!(money_pot_params)

    redirect_to money_pot
  end

  private
  def money_pot_params
    params.require(:money_pot).permit(:title, :value)
  end

  def get_current_money_pot
    MoneyPot.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.money_pot_id = params[:money_pot_id]
    @transaction.user_id = current_user.id
    @money_pot = get_current_money_pot

    if @transaction.save
      redirect_to @money_pot
    else
      flash.now[:error] = "Could not save money pot"
      render action: "new"
    end
  end

  private
  def transaction_params
    params.require(:transaction).permit(:comment, :value, :user_id)
  end

  def get_current_money_pot
    MoneyPot.find(params[:money_pot_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/money_pots_helper.rb
module MoneyPotsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WgCashSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <!-- Compiled and minified CSS -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

 <!-- Compiled and minified JavaScript -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <div class="nav-wrapper">
      <%= link_to "WG Kasse", root_path, class: "brand-logo" %>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
        <li>
          <span>
            Logged in as <%= current_user.username ? current_user.username : current_user.email %>
          </span>
        </li>
        <li>
          <%= link_to "Edit profile", edit_user_registration_path %>
        </li>
        <li>
          <a href="#!">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          </a>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>

<div class="container">
  <div class="row">
    <div class="col s12">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
     </div>
  </div>
<%= yield %>
</div>

</body>
</html>

app/views/money_pots/_form.html.erb
<%= simple_form_for @money_pot do |f| %>
  <%= f.input :title %>
  <%= f.button :submit %>
<% end %>

app/views/money_pots/edit.html.erb
<h2>Edit <%= @money_pot.title %></h2>

<%= render "form" %>

app/views/money_pots/index.html.erb
<% if @money_pots.empty? %>
  <h1>There are no active money pots</h1>
<% else %>
  <h1>List of current active Pots</h1>
<% end %>

<ul>
<% @money_pots.each do |money_pot| %>
  <li><%= link_to money_pot.title, money_pot %></li>
<% end %>
</ul>

app/views/money_pots/new.html.erb
<h2>Create a new money pot</h2>

<%= render "form" %>

app/views/money_pots/show.html.erb
<div class="row">
  <div class="col s12">
    <%= link_to "Edit", edit_money_pot_path(@money_pot) %>
  </div>

  <div class="col s12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">
          '<%= @money_pot.title %></h1>'
        </span>
        <p>
          Active since <%= @money_pot.created_at.strftime("%d-%m-%Y (%H:%M)") %>
        </p>
        <p>
          Created by <i><%= @money_pot.user.email %></i>
        </p>
      </div>
      <div class="card-action white-text">
        Current value: <%= number_to_currency(@transactions_value) %>
      </div>
    </div>
  </div>

  <div class="col s6">
    <h4>Last 5 transactions</h4>
    <div class="collection">
      <% if @transactions.empty? %>
        <a href="#" class="collection-item">There are no transactions yet.</a>
      <% else %>
        <% @transactions.limit(5).each do |transaction| %>
          <a class="collection-item <%= transaction.value >= 0 ? 'green lighten-3' : 'red lighten-3' %>">
            <%= transaction.user.email %> logged at <%= transaction.created_at.strftime("%d-%m-%Y (%H:%M)")  %> a
            transaction for <%= number_to_currency(transaction.value) %> (<%= transaction.comment %>)
          </a>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col s6">
    <h4>Add new transaction
    <%= render :partial => "transactions/new", :object => @transaction %>
  </div>

  <div class="col s12">
    <h2>Transaction trends</h2>
    <%= area_chart @transactions.group(:created_at).sum(:value) %>
  </div>
</div>

app/views/transactions/_form.html.erb
<%= simple_form_for @transaction do |f| %>
  <%= f.input :comment %>
  <%= f.input :value %>
  <%= f.button :submit %>
<% end %>

app/views/transactions/_new.html.erb
<%= simple_form_for [@money_pot, @transaction] do |f| %>
  <%= f.input :comment %>
  <%= f.input :value %>
  <%= f.button :submit, "New transaction" %>
<% end %>